spring:
    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/
    resources: # Static resources
        static-locations: file:src/main/resources/static/
        cache:
        period: 0

    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
        generate-unique-name: false
        name: Games
        jpa:
            spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
