spring:
    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/

---
spring:
    config:
        activate:
            on-profile: psdev
    datasource:
        username: ${DATABASE_USER_NAME}
        password: ${DATABASE_USER_PASSWORD}
        url: ${DATABASE_PATH}
        driverClassName: ${DATABASE_DRIVER_CLASS_NAME}
        generate-unique-name: false
        name: ${DATABASE_NAME}
        jpa:
            database-platform: ${DATABASE_PLATFORM}
            hibernate:
                ddl-auto: create

        h2:
            console:
                enabled: true
                settings:
                    web-allow-others: true
logging:
    file:
        name: log/log.log